### ISSUE TITLE
Feature request: Sprite/Portrait history

### ISSUE THREAD

**Issue by Chesyon** [PMDCollab/PMD-collab-wiki#49]
It'd be very helpful if each mon's page showed it's sprite and portrait history, like the !portraithistory and !spritehistory Spritebot commands.
![portrait history on site mockup](https://github.com/PMDCollab/PMD-collab-wiki/assets/55322011/249828d4-bd03-4fb7-8ae0-ea5bfb45eaa7)

**Comment by keldaan-ag** [comment]
If we want to solve this issue, i would need those informations in the spriteServer @theCapypara 

```
type MonsterFormPortraits {
   """
   List of all modifications made to those portraits since its creation
   """
   history: [MonsterHistory]
  ...
}

type MonsterFormSprites {
  """
  List of all modifications made to those sprites since its creation
  """
   history: [MonsterHistory]
  ...
}

type MonsterHistory {
  credit: Credit
  modifiedDate: DateTimeUtc
  modifications: [string]
}
```

**Comment by theCapypara** [comment]
Hi! I implemented this. https://github.com/PMDCollab/spritecollab-srv/commit/3f3da05eff87254e3509d33290733f0f390589c7
Please query the history field lazily, do not load it with all Pokémon at once, only when a Pokémon is actually opened. It's not cheap to compute.

Additionally the history entries have an additional "[obsolete](https://github.com/PMDCollab/spritecollab-srv/commit/3f3da05eff87254e3509d33290733f0f390589c7#diff-cfb402317f9a1267396cd28c72ab83f4236dca6ebbf2f87ed850f2b82da5862dR177)" boolean field.

**Comment by keldaan-ag** [comment]
feature implemented
![image](https://github.com/PMDCollab/PMD-collab-wiki/assets/24555243/31f8836b-7307-4df4-8010-4f6ec549a6b9)
